In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

### Set the environment variable to suppress the warning from tensoflow
```bash
export TF_CPP_MIN_LOG_LEVEL="2"
```

In [2]:
dataset = pd.read_csv("./data/storepurchasedata_large.csv")

In [3]:
dataset.shape

(1554, 3)

In [4]:
dataset.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   60000          1

In [5]:
# Get the IDV and DV in X and y variables
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [6]:
# Split the data to train & test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

In [7]:
# Standard scaling the data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
X_train

array([[-0.09347628,  0.22152545],
       [ 1.22167788, -0.53416893],
       [-1.06554674,  0.41044905],
       ...,
       [ 1.2788585 ,  0.41044905],
       [-0.95118551,  0.22152545],
       [-1.2942692 , -1.431556  ]])

In [9]:
# Build the tensorflow model
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])

In [10]:
# compile the model 
model.compile(optimizer='adam',
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy'])

In [11]:
model.fit(X_train, y_train, epochs=50)

Epoch 1/50
39/39 [==============================] - 0s 740us/step - loss: 0.7176 - accuracy: 0.4730
Epoch 2/50
39/39 [==============================] - 0s 712us/step - loss: 0.5344 - accuracy: 0.7007
Epoch 3/50
39/39 [==============================] - 0s 744us/step - loss: 0.4431 - accuracy: 0.7506
Epoch 4/50
39/39 [==============================] - 0s 663us/step - loss: 0.3851 - accuracy: 0.8375
Epoch 5/50
39/39 [==============================] - 0s 787us/step - loss: 0.3357 - accuracy: 0.8866
Epoch 6/50
39/39 [==============================] - 0s 784us/step - loss: 0.2867 - accuracy: 0.9477
Epoch 7/50
39/39 [==============================] - 0s 803us/step - loss: 0.2428 - accuracy: 0.9590
Epoch 8/50
39/39 [==============================] - 0s 788us/step - loss: 0.2057 - accuracy: 0.9566
Epoch 9/50
39/39 [==============================] - 0s 669us/step - loss: 0.1778 - accuracy: 0.9558
Epoch 10/50
39/39 [==============================] - 0s 720us/step - loss: 0.1587 - accuracy: 0.9549

In [14]:
loss, accuracy = model.evaluate(X_test, y_test)

10/10 [==============================] - 0s 659us/step - loss: 0.1041 - accuracy: 0.9550


In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 2)                 22        
                                                                 
Total params: 162
Trainable params: 162
Non-trainable params: 0
_________________________________________________________________


In [16]:
prediction1 = model.predict(sc.transform(np.array([[42, 50000]])))[:,1]
prediction1

1/1 [==============================] - 0s 44ms/step


array([0.6596004], dtype=float32)

In [17]:
prediction2 = model.predict(sc.transform(np.array([[20, 40000]])))[:,1]
prediction2

1/1 [==============================] - 0s 14ms/step


array([0.00894171], dtype=float32)

In [18]:
model.save('consumer_behavior_model/1')

INFO:tensorflow:Assets written to: consumer_behavior_model/1/assets


INFO:tensorflow:Assets written to: consumer_behavior_model/1/assets


In [19]:
!ls

Build_Tensorflow_model.ipynb  consumer_behavior_model  sc.pickle
client-code.py		      data		       server-code.py


In [21]:
# variable - weights & checkpoints are saved
# saved_model.pb - protoblob format the model file is saved
!ls consumer_behavior_model/1

assets	fingerprint.pb	keras_metadata.pb  saved_model.pb  variables


 ## Loading the saved model file

In [22]:
from tensorflow.keras.models import load_model

In [23]:
cust_model = load_model('consumer_behavior_model/1/')

In [25]:
prediction  = cust_model.predict(sc.transform(np.array([[20, 40000]])))[:,1]

1/1 [==============================] - 0s 11ms/step


In [26]:
prediction

array([0.00814757], dtype=float32)