In [1]:
## Import Package
import numpy as np
import pandas as pd

In [6]:
# Load the data
training_data = pd.read_csv('./data/storepurchasedata.csv')

In [7]:
# home/not
training_data.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   50000          1

In [17]:
# Read the IDV and DV's in X & Y respectively
X = training_data.iloc[:, :-1].values
y = training_data.iloc[:,-1].values

In [33]:
# Split the training data to train & test split - 80% - Train / 20% Test 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.20, random_state=0)

In [34]:
# Shape of Train and Test data
X_train.shape, X_test.shape

((32, 2), (8, 2))

In [35]:
X_train[:5]

array([[   36, 60000],
       [   47, 55000],
       [   45, 60000],
       [   56, 45000],
       [   58, 80000]])

In [36]:
training_data.describe()

Age        Salary  Purchased
count  40.000000     40.000000  40.000000
mean   38.100000  49525.000000   0.550000
std    12.557151  19046.484971   0.503831
min    18.000000  20000.000000   0.000000
25%    27.750000  35000.000000   0.000000
50%    37.500000  48500.000000   1.000000
75%    47.250000  60000.000000   1.000000
max    60.000000  95000.000000   1.000000

In [49]:
# Z-score - -1 to 1
# (x-mean)/stddv
# (42-38)/12.55


# noralmilize 0 -1
# abs(13-38)/12.55

1.99203187250996

In [38]:
# Standard scaler to scale the data to -1 to 1 range
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [41]:
X_test[:5]

array([[ 0.08291162,  0.54818427],
       [-0.0686982 ,  0.19018638],
       [ 0.31032636,  0.13904382],
       [-1.28157679,  0.03675871],
       [-0.82674732,  1.5710354 ]])

<img src="knn-model.png">

In [50]:
# K-Nearest Neighbour
from sklearn.neighbors import KNeighborsClassifier
# minkowski is for ecledian distance
classifier = KNeighborsClassifier(n_neighbors = 5, metric='minkowski', p=2)

In [51]:
# Model training
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [53]:
# Predict on the test data
y_pred = classifier.predict(X_test)
y_prob = classifier.predict_proba(X_test)[:,1]

In [56]:
X_test

array([[ 0.08291162,  0.54818427],
       [-0.0686982 ,  0.19018638],
       [ 0.31032636,  0.13904382],
       [-1.28157679,  0.03675871],
       [-0.82674732,  1.5710354 ],
       [-0.44772276, -0.11666896],
       [ 0.53774109, -1.39523286],
       [-0.75094241, -0.47466685]])

In [54]:
y_pred

array([1, 1, 1, 0, 1, 0, 0, 0])

In [57]:
y_test

array([1, 1, 1, 1, 1, 0, 0, 0])

In [55]:
y_prob

array([1. , 0.6, 0.8, 0. , 0.8, 0.2, 0.4, 0. ])

In [12]:
# Confusion metrics
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[3, 0],
       [1, 4]])

In [62]:
np.array([[4, 1], [0, 3]])

array([[4, 1],
       [0, 3]])

In [59]:
# Calculate the accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.875


In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.75      1.00      0.86         3
           1       1.00      0.80      0.89         5

    accuracy                           0.88         8
   macro avg       0.88      0.90      0.87         8
weighted avg       0.91      0.88      0.88         8



## Test on a new data

In [76]:
classifier.predict(sc.transform(np.array([[18, 50000]])))

array([0])

In [ ]:
new_prediction = classifier.predict(sc.transform(np.array([[40,20000]])))
new_prediction_proba = classifier.predict_proba(sc.transform(np.array([[40,20000]])))[:,1]

In [15]:
new_pred = classifier.predict(sc.transform(np.array([[42,50000]])))
new_pred_proba = classifier.predict_proba(sc.transform(np.array([[42,50000]])))[:,1]

In [17]:
new_prediction, new_pred

(array([0]), array([1]))

## Save the model & standard scaler to a pickle file

In [78]:
import pickle
model_file = "classifier.pickle"
pickle.dump(classifier, open(model_file,'wb'))

In [79]:
scaler_file = "sc.pickle"
pickle.dump(sc, open(scaler_file,'wb'))

In [80]:
!ls

 classifier.pickle   knn-model.png	  ml_pipeline.py
 data		    'ML Pipeline.ipynb'   sc.pickle
